# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths

# require openZeppelin contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0

# path remapping to support OpenZeppelin imports with npm-style path
compiler:
    solc:
      version: 0.6.12
      remappings:
        - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0"

reports:
  exclude_contracts:
    - SafeMath
